// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwVWtvu4uDiNrUh5Wdgnnnf_y8fUmsQr0',
    appId: '1:699776176131:web:8d142e8ea9def5db3dfe36',
    messagingSenderId: '699776176131',
    projectId: 'clothes-store-77b8b',
    authDomain: 'clothes-store-77b8b.firebaseapp.com',
    storageBucket: 'clothes-store-77b8b.firebasestorage.app',
    measurementId: 'G-LSKQHENTWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1AsBLpNdP8TqMW7Ldt-Pip5o3sx26E_A',
    appId: '1:699776176131:android:1bfd7a940e71d7983dfe36',
    messagingSenderId: '699776176131',
    projectId: 'clothes-store-77b8b',
    storageBucket: 'clothes-store-77b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYE0x5y0TyCbiTmKwotaiV_RNnhV4TS1Y',
    appId: '1:699776176131:ios:27888e063bda7ca93dfe36',
    messagingSenderId: '699776176131',
    projectId: 'clothes-store-77b8b',
    storageBucket: 'clothes-store-77b8b.firebasestorage.app',
    iosBundleId: 'com.example.clothesStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYE0x5y0TyCbiTmKwotaiV_RNnhV4TS1Y',
    appId: '1:699776176131:ios:27888e063bda7ca93dfe36',
    messagingSenderId: '699776176131',
    projectId: 'clothes-store-77b8b',
    storageBucket: 'clothes-store-77b8b.firebasestorage.app',
    iosBundleId: 'com.example.clothesStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwVWtvu4uDiNrUh5Wdgnnnf_y8fUmsQr0',
    appId: '1:699776176131:web:b47793b9cf2747d23dfe36',
    messagingSenderId: '699776176131',
    projectId: 'clothes-store-77b8b',
    authDomain: 'clothes-store-77b8b.firebaseapp.com',
    storageBucket: 'clothes-store-77b8b.firebasestorage.app',
    measurementId: 'G-225G4BCR2F',
  );
}
